/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...catchAll]': RouteRecordInfo<'/[...catchAll]', '/:catchAll(.*)', { catchAll: ParamValue<true> }, { catchAll: ParamValue<false> }>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/analytics': RouteRecordInfo<'/dashboard/analytics', '/dashboard/analytics', Record<never, never>, Record<never, never>>,
    '/dashboard/config': RouteRecordInfo<'/dashboard/config', '/dashboard/config', Record<never, never>, Record<never, never>>,
    '/dashboard/dashboard/': RouteRecordInfo<'/dashboard/dashboard/', '/dashboard/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/Nginx': RouteRecordInfo<'/dashboard/Nginx', '/dashboard/Nginx', Record<never, never>, Record<never, never>>,
    '/dashboard/profile': RouteRecordInfo<'/dashboard/profile', '/dashboard/profile', Record<never, never>, Record<never, never>>,
    '/dashboard/profile/': RouteRecordInfo<'/dashboard/profile/', '/dashboard/profile', Record<never, never>, Record<never, never>>,
    '/dashboard/rsnapshot': RouteRecordInfo<'/dashboard/rsnapshot', '/dashboard/rsnapshot', Record<never, never>, Record<never, never>>,
    '/dashboard/servers': RouteRecordInfo<'/dashboard/servers', '/dashboard/servers', Record<never, never>, Record<never, never>>,
    '/dashboard/settings': RouteRecordInfo<'/dashboard/settings', '/dashboard/settings', Record<never, never>, Record<never, never>>,
  }
}
