/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...catchAll]': RouteRecordInfo<'/[...catchAll]', '/:catchAll(.*)', { catchAll: ParamValue<true> }, { catchAll: ParamValue<false> }>,
    '/services/nginx/': RouteRecordInfo<'/services/nginx/', '/services/nginx', Record<never, never>, Record<never, never>>,
    '/services/nginx/certificates': RouteRecordInfo<'/services/nginx/certificates', '/services/nginx/certificates', Record<never, never>, Record<never, never>>,
    '/services/nginx/servers': RouteRecordInfo<'/services/nginx/servers', '/services/nginx/servers', Record<never, never>, Record<never, never>>,
    '/services/rsnapshot/': RouteRecordInfo<'/services/rsnapshot/', '/services/rsnapshot', Record<never, never>, Record<never, never>>,
    '/site/': RouteRecordInfo<'/site/', '/site', Record<never, never>, Record<never, never>>,
    '/site/analytics/': RouteRecordInfo<'/site/analytics/', '/site/analytics', Record<never, never>, Record<never, never>>,
    '/site/profile/': RouteRecordInfo<'/site/profile/', '/site/profile', Record<never, never>, Record<never, never>>,
  }
}
